[market]
data_path = "data/market"
symbols = [
  "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BPCL",
  "BHARTIARTL", "BRITANNIA", "CIPLA", "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT", "GRASIM", "HCLTECH",
  "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "ITC", "INDUSINDBK", "INFY",
  "JSWSTEEL", "KOTAKBANK", "LT", "M&M", "MARUTI", "NTPC", "NESTLEIND", "ONGC", "POWERGRID", "RELIANCE",
  "SBILIFE", "SBIN", "SUNPHARMA", "TCS", "TATACONSUM", "TATAMOTORS", "TATASTEEL", "TECHM", "TITAN",
  "UPL", "ULTRACEMCO", "WIPRO"
]
data_start_date = "2024-01-01"
data_end_date = "2024-12-31"

[trading]
initial_capital = 100000
position_size_limit = 0.2
stop_loss = 0.05
take_profit = 0.1

[agent]
model = "gpt-4"
risk_profile = "moderate"
personality = "default"
risk_tolerance = "medium"
investment_style = "balanced"
time_horizon = "medium_term"

[chat]
system_prompt = "You are an expert Indian stock market trader."
max_tokens = 500
temperature = 0.7
top_p = 1.0
top_k = 40

[memory]
max_days = 30
short_term_capacity = 100
long_term_capacity = 1000
relevance_threshold = 0.5